-- ============================================
-- MIGRACIÓN 046: poblar gif_key + poda de catálogo
-- gif_key = id de producto en Gym Visual; la URL pública se construye en @gym/shared
-- Generado desde la revisión final del catálogo (compra pedido 57847)
-- ============================================

-- 1. GIF en ejercicios de SISTEMA (255)
UPDATE exercises SET gif_key = '1519' WHERE name_en = 'Barbell Bench Press' AND is_system = true;
UPDATE exercises SET gif_key = '15967' WHERE name_en = 'Cable Pullover' AND is_system = true;
UPDATE exercises SET gif_key = '1524' WHERE name_en = 'Close-Grip Bench Press' AND is_system = true;
UPDATE exercises SET gif_key = '3073' WHERE name_en = 'Converging Machine Chest Press' AND is_system = true;
UPDATE exercises SET gif_key = '1527' WHERE name_en = 'Decline Barbell Bench Press' AND is_system = true;
UPDATE exercises SET gif_key = '1795' WHERE name_en = 'Decline Dumbbell Fly' AND is_system = true;
UPDATE exercises SET gif_key = '1794' WHERE name_en = 'Decline Dumbbell Press' AND is_system = true;
UPDATE exercises SET gif_key = '1773' WHERE name_en = 'Decline Push-Ups' AND is_system = true;
UPDATE exercises SET gif_key = '1776' WHERE name_en = 'Diamond Push-Ups' AND is_system = true;
UPDATE exercises SET gif_key = '1782' WHERE name_en = 'Dumbbell Bench Press' AND is_system = true;
UPDATE exercises SET gif_key = '8890' WHERE name_en = 'Dumbbell Floor Press' AND is_system = true;
UPDATE exercises SET gif_key = '1801' WHERE name_en = 'Dumbbell Fly' AND is_system = true;
UPDATE exercises SET gif_key = '9923' WHERE name_en = 'Dumbbell Hex Press' AND is_system = true;
UPDATE exercises SET gif_key = '1876' WHERE name_en = 'Dumbbell Pullover' AND is_system = true;
UPDATE exercises SET gif_key = '1720' WHERE name_en = 'High Cable Crossover' AND is_system = true;
UPDATE exercises SET gif_key = '1541' WHERE name_en = 'Incline Barbell Bench Press' AND is_system = true;
UPDATE exercises SET gif_key = '1820' WHERE name_en = 'Incline Dumbbell Fly' AND is_system = true;
UPDATE exercises SET gif_key = '1807' WHERE name_en = 'Incline Dumbbell Press' AND is_system = true;
UPDATE exercises SET gif_key = '1992' WHERE name_en = 'Incline Push-Ups' AND is_system = true;
UPDATE exercises SET gif_key = '1672' WHERE name_en = 'Low Cable Crossover' AND is_system = true;
UPDATE exercises SET gif_key = '10243' WHERE name_en = 'Machine Chest Press' AND is_system = true;
UPDATE exercises SET gif_key = '4788' WHERE name_en = 'Machine Pullover' AND is_system = true;
UPDATE exercises SET gif_key = '17880' WHERE name_en = 'Mid Cable Crossover' AND is_system = true;
UPDATE exercises SET gif_key = '2093' WHERE name_en = 'Pec Deck Machine Fly' AND is_system = true;
UPDATE exercises SET gif_key = '23011' WHERE name_en = 'Push-Ups' AND is_system = true;
UPDATE exercises SET gif_key = '25289' WHERE name_en = 'Single-Arm Cable Chest Press' AND is_system = true;
UPDATE exercises SET gif_key = '2231' WHERE name_en = 'Smith Machine Bench Press' AND is_system = true;
UPDATE exercises SET gif_key = '2240' WHERE name_en = 'Smith Machine Incline Press' AND is_system = true;
UPDATE exercises SET gif_key = '13346' WHERE name_en = 'Back Extensions' AND is_system = true;
UPDATE exercises SET gif_key = '1592' WHERE name_en = 'Barbell Shrug' AND is_system = true;
UPDATE exercises SET gif_key = '5556' WHERE name_en = 'Behind-the-Neck Lat Pulldown' AND is_system = true;
UPDATE exercises SET gif_key = '3098' WHERE name_en = 'Chin-Ups' AND is_system = true;
UPDATE exercises SET gif_key = '2516' WHERE name_en = 'Close-Grip Lat Pulldown' AND is_system = true;
UPDATE exercises SET gif_key = '1526' WHERE name_en = 'Conventional Deadlift' AND is_system = true;
UPDATE exercises SET gif_key = '1907' WHERE name_en = 'Dumbbell Shrug' AND is_system = true;
UPDATE exercises SET gif_key = '1660' WHERE name_en = 'High Cable Row' AND is_system = true;
UPDATE exercises SET gif_key = '8343' WHERE name_en = 'Incline Bench Dumbbell Row' AND is_system = true;
UPDATE exercises SET gif_key = '7791' WHERE name_en = 'Incline Bench Y-Raise' AND is_system = true;
UPDATE exercises SET gif_key = '1998' WHERE name_en = 'Inverted Row' AND is_system = true;
UPDATE exercises SET gif_key = '1508' WHERE name_en = 'Machine Assisted Pull-Ups' AND is_system = true;
UPDATE exercises SET gif_key = '2085' WHERE name_en = 'Machine Row' AND is_system = true;
UPDATE exercises SET gif_key = '10105' WHERE name_en = 'Meadows Row' AND is_system = true;
UPDATE exercises SET gif_key = '10247' WHERE name_en = 'Neutral-Grip Lat Pulldown' AND is_system = true;
UPDATE exercises SET gif_key = '13420' WHERE name_en = 'Neutral-Grip Pull-Ups' AND is_system = true;
UPDATE exercises SET gif_key = '1521' WHERE name_en = 'Overhand Barbell Row' AND is_system = true;
UPDATE exercises SET gif_key = '1691' WHERE name_en = 'Overhand Lat Pulldown' AND is_system = true;
UPDATE exercises SET gif_key = '6574' WHERE name_en = 'Pendlay Row' AND is_system = true;
UPDATE exercises SET gif_key = '2145' WHERE name_en = 'Pull-Ups' AND is_system = true;
UPDATE exercises SET gif_key = '1568' WHERE name_en = 'Rack Pull' AND is_system = true;
UPDATE exercises SET gif_key = '6505' WHERE name_en = 'Renegade Row' AND is_system = true;
UPDATE exercises SET gif_key = '3093' WHERE name_en = 'Rope Seated Cable Row' AND is_system = true;
UPDATE exercises SET gif_key = '1711' WHERE name_en = 'Seated Cable Row' AND is_system = true;
UPDATE exercises SET gif_key = '10911' WHERE name_en = 'Single-Arm Dumbbell Row' AND is_system = true;
UPDATE exercises SET gif_key = '2654' WHERE name_en = 'Single-Arm Lat Pulldown' AND is_system = true;
UPDATE exercises SET gif_key = '22117' WHERE name_en = 'Single-Arm Seated Cable Row' AND is_system = true;
UPDATE exercises SET gif_key = '2250' WHERE name_en = 'Smith Machine Shrug' AND is_system = true;
UPDATE exercises SET gif_key = '1731' WHERE name_en = 'Straight-Arm Cable Pulldown' AND is_system = true;
UPDATE exercises SET gif_key = '1615' WHERE name_en = 'Sumo Deadlift' AND is_system = true;
UPDATE exercises SET gif_key = '2645' WHERE name_en = 'T-Bar Row' AND is_system = true;
UPDATE exercises SET gif_key = '1616' WHERE name_en = 'Underhand Barbell Row' AND is_system = true;
UPDATE exercises SET gif_key = '1738' WHERE name_en = 'Underhand Lat Pulldown' AND is_system = true;
UPDATE exercises SET gif_key = '5623' WHERE name_en = 'V-Bar Lat Pulldown' AND is_system = true;
UPDATE exercises SET gif_key = '6668' WHERE name_en = 'V-Bar Seated Cable Row' AND is_system = true;
UPDATE exercises SET gif_key = '13030' WHERE name_en = 'Weighted Back Extensions' AND is_system = true;
UPDATE exercises SET gif_key = '2322' WHERE name_en = 'Weighted Pull-Ups' AND is_system = true;
UPDATE exercises SET gif_key = '4905' WHERE name_en = 'Wide-Grip Lat Pulldown' AND is_system = true;
UPDATE exercises SET gif_key = '1711' WHERE name_en = 'Wide-Grip Seated Cable Row' AND is_system = true;
UPDATE exercises SET gif_key = '4176' WHERE name_en = 'Arnold Press' AND is_system = true;
UPDATE exercises SET gif_key = '4746' WHERE name_en = 'Band External Rotation' AND is_system = true;
UPDATE exercises SET gif_key = '12292' WHERE name_en = 'Band Pull-Apart' AND is_system = true;
UPDATE exercises SET gif_key = '1535' WHERE name_en = 'Barbell Front Raise' AND is_system = true;
UPDATE exercises SET gif_key = '2651' WHERE name_en = 'Barbell Push Press' AND is_system = true;
UPDATE exercises SET gif_key = '1618' WHERE name_en = 'Barbell Upright Row' AND is_system = true;
UPDATE exercises SET gif_key = '1728' WHERE name_en = 'Cable External Rotation' AND is_system = true;
UPDATE exercises SET gif_key = '18422' WHERE name_en = 'Cable Face Pull' AND is_system = true;
UPDATE exercises SET gif_key = '1655' WHERE name_en = 'Cable Front Raise' AND is_system = true;
UPDATE exercises SET gif_key = '4301' WHERE name_en = 'Cable Lateral Raise' AND is_system = true;
UPDATE exercises SET gif_key = '20003' WHERE name_en = 'Cable Reverse Fly' AND is_system = true;
UPDATE exercises SET gif_key = '1739' WHERE name_en = 'Cable Upright Row' AND is_system = true;
UPDATE exercises SET gif_key = '2344' WHERE name_en = 'Dumbbell External Rotation' AND is_system = true;
UPDATE exercises SET gif_key = '1803' WHERE name_en = 'Dumbbell Front Raise' AND is_system = true;
UPDATE exercises SET gif_key = '1835' WHERE name_en = 'Dumbbell Lateral Raise' AND is_system = true;
UPDATE exercises SET gif_key = '23676' WHERE name_en = 'Dumbbell Lu Raise' AND is_system = true;
UPDATE exercises SET gif_key = '1884' WHERE name_en = 'Dumbbell Reverse Fly' AND is_system = true;
UPDATE exercises SET gif_key = '1938' WHERE name_en = 'Dumbbell Upright Row' AND is_system = true;
UPDATE exercises SET gif_key = '1884' WHERE name_en = 'Incline Bench Reverse Fly' AND is_system = true;
UPDATE exercises SET gif_key = '2051' WHERE name_en = 'Kettlebell Shoulder Press' AND is_system = true;
UPDATE exercises SET gif_key = '13676' WHERE name_en = 'Landmine Press' AND is_system = true;
UPDATE exercises SET gif_key = '2081' WHERE name_en = 'Machine Lateral Raise' AND is_system = true;
UPDATE exercises SET gif_key = '2927' WHERE name_en = 'Machine Shoulder Press' AND is_system = true;
UPDATE exercises SET gif_key = '2315' WHERE name_en = 'Plate Front Raise' AND is_system = true;
UPDATE exercises SET gif_key = '2099' WHERE name_en = 'Reverse Pec Deck Fly' AND is_system = true;
UPDATE exercises SET gif_key = '2514' WHERE name_en = 'Seated Barbell Overhead Press' AND is_system = true;
UPDATE exercises SET gif_key = '1906' WHERE name_en = 'Seated Dumbbell Shoulder Press' AND is_system = true;
UPDATE exercises SET gif_key = '13557' WHERE name_en = 'Single-Arm Landmine Press' AND is_system = true;
UPDATE exercises SET gif_key = '2248' WHERE name_en = 'Smith Machine Shoulder Press' AND is_system = true;
UPDATE exercises SET gif_key = '2617' WHERE name_en = 'Standing Barbell Overhead Press' AND is_system = true;
UPDATE exercises SET gif_key = '1928' WHERE name_en = 'Standing Dumbbell Shoulder Press' AND is_system = true;
UPDATE exercises SET gif_key = '1778' WHERE name_en = 'Alternating Dumbbell Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1532' WHERE name_en = 'Barbell Drag Curl' AND is_system = true;
UPDATE exercises SET gif_key = '12354' WHERE name_en = 'Bayesian Cable Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1790' WHERE name_en = 'Dumbbell Concentration Curl' AND is_system = true;
UPDATE exercises SET gif_key = '15410' WHERE name_en = 'Dumbbell Drag Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1806' WHERE name_en = 'Dumbbell Hammer Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1873' WHERE name_en = 'Dumbbell Preacher Curl' AND is_system = true;
UPDATE exercises SET gif_key = '3612' WHERE name_en = 'Dumbbell Spider Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1940' WHERE name_en = 'Dumbbell Zottman Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1948' WHERE name_en = 'EZ-Bar Curl' AND is_system = true;
UPDATE exercises SET gif_key = '16019' WHERE name_en = 'EZ-Bar Preacher Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1955' WHERE name_en = 'EZ-Bar Spider Curl' AND is_system = true;
UPDATE exercises SET gif_key = '3573' WHERE name_en = 'High Cable Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1808' WHERE name_en = 'Incline Dumbbell Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1821' WHERE name_en = 'Incline Dumbbell Hammer Curl' AND is_system = true;
UPDATE exercises SET gif_key = '14826' WHERE name_en = 'Kettlebell Curl' AND is_system = true;
UPDATE exercises SET gif_key = '12122' WHERE name_en = 'Machine Bicep Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1659' WHERE name_en = 'Rope Cable Hammer Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1787' WHERE name_en = 'Simultaneous Dumbbell Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1649' WHERE name_en = 'Straight Bar Cable Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1525' WHERE name_en = 'Straight Barbell Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1554' WHERE name_en = 'Barbell Skull Crusher' AND is_system = true;
UPDATE exercises SET gif_key = '3765' WHERE name_en = 'Bench Dips' AND is_system = true;
UPDATE exercises SET gif_key = '3740' WHERE name_en = 'Cable Tricep Kickback' AND is_system = true;
UPDATE exercises SET gif_key = '1852' WHERE name_en = 'Dumbbell Skull Crusher' AND is_system = true;
UPDATE exercises SET gif_key = '1937' WHERE name_en = 'Dumbbell Tate Press' AND is_system = true;
UPDATE exercises SET gif_key = '3751' WHERE name_en = 'Dumbbell Tricep Kickback' AND is_system = true;
UPDATE exercises SET gif_key = '8882' WHERE name_en = 'EZ-Bar Skull Crusher' AND is_system = true;
UPDATE exercises SET gif_key = '1546' WHERE name_en = 'JM Press' AND is_system = true;
UPDATE exercises SET gif_key = '4575' WHERE name_en = 'Machine Tricep Extension' AND is_system = true;
UPDATE exercises SET gif_key = '10167' WHERE name_en = 'Overhead Cable Tricep Extension' AND is_system = true;
UPDATE exercises SET gif_key = '5936' WHERE name_en = 'Overhead Dumbbell Tricep Extension' AND is_system = true;
UPDATE exercises SET gif_key = '4318' WHERE name_en = 'Overhead Rope Cable Tricep Extension' AND is_system = true;
UPDATE exercises SET gif_key = '5240' WHERE name_en = 'Parallel Bar Dips' AND is_system = true;
UPDATE exercises SET gif_key = '2674' WHERE name_en = 'Rope Tricep Pushdown' AND is_system = true;
UPDATE exercises SET gif_key = '15432' WHERE name_en = 'Single-Arm Overhead Dumbbell Tricep Extension' AND is_system = true;
UPDATE exercises SET gif_key = '3735' WHERE name_en = 'Single-Arm Tricep Pushdown' AND is_system = true;
UPDATE exercises SET gif_key = '3469' WHERE name_en = 'Straight Bar Tricep Pushdown' AND is_system = true;
UPDATE exercises SET gif_key = '3470' WHERE name_en = 'Underhand Tricep Pushdown' AND is_system = true;
UPDATE exercises SET gif_key = '12140' WHERE name_en = 'V-Bar Tricep Pushdown' AND is_system = true;
UPDATE exercises SET gif_key = '2311' WHERE name_en = 'Weighted Bench Dips' AND is_system = true;
UPDATE exercises SET gif_key = '3801' WHERE name_en = 'Weighted Parallel Bar Dips' AND is_system = true;
UPDATE exercises SET gif_key = '1574' WHERE name_en = 'Barbell Reverse Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1576' WHERE name_en = 'Barbell Reverse Wrist Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1624' WHERE name_en = 'Barbell Wrist Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1699' WHERE name_en = 'Cable Reverse Curl' AND is_system = true;
UPDATE exercises SET gif_key = '11528' WHERE name_en = 'Dead Hang' AND is_system = true;
UPDATE exercises SET gif_key = '1886' WHERE name_en = 'Dumbbell Reverse Wrist Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1865' WHERE name_en = 'Dumbbell Wrist Curl' AND is_system = true;
UPDATE exercises SET gif_key = '15918' WHERE name_en = 'EZ-Bar Reverse Curl' AND is_system = true;
UPDATE exercises SET gif_key = '4220' WHERE name_en = 'Farmer''s Walk' AND is_system = true;
UPDATE exercises SET gif_key = '4791' WHERE name_en = 'Hand Gripper' AND is_system = true;
UPDATE exercises SET gif_key = '2513' WHERE name_en = 'Plate Pinch Hold' AND is_system = true;
UPDATE exercises SET gif_key = '2340' WHERE name_en = 'Wrist Roller' AND is_system = true;
UPDATE exercises SET gif_key = '4297' WHERE name_en = 'Barbell Bulgarian Split Squat' AND is_system = true;
UPDATE exercises SET gif_key = '1548' WHERE name_en = 'Barbell Lunges' AND is_system = true;
UPDATE exercises SET gif_key = '1612' WHERE name_en = 'Barbell Step-Up' AND is_system = true;
UPDATE exercises SET gif_key = '6763' WHERE name_en = 'Belt Squat' AND is_system = true;
UPDATE exercises SET gif_key = '1911' WHERE name_en = 'Dumbbell Bulgarian Split Squat' AND is_system = true;
UPDATE exercises SET gif_key = '3795' WHERE name_en = 'Dumbbell Goblet Squat' AND is_system = true;
UPDATE exercises SET gif_key = '12369' WHERE name_en = 'Dumbbell Lateral Lunges' AND is_system = true;
UPDATE exercises SET gif_key = '1837' WHERE name_en = 'Dumbbell Lunges' AND is_system = true;
UPDATE exercises SET gif_key = '1882' WHERE name_en = 'Dumbbell Reverse Lunges' AND is_system = true;
UPDATE exercises SET gif_key = '1932' WHERE name_en = 'Dumbbell Step-Up' AND is_system = true;
UPDATE exercises SET gif_key = '1536' WHERE name_en = 'Front Squat' AND is_system = true;
UPDATE exercises SET gif_key = '2226' WHERE name_en = 'Hack Squat Machine' AND is_system = true;
UPDATE exercises SET gif_key = '2909' WHERE name_en = 'High-Bar Back Squat' AND is_system = true;
UPDATE exercises SET gif_key = '6764' WHERE name_en = 'Horizontal Leg Press' AND is_system = true;
UPDATE exercises SET gif_key = '2222' WHERE name_en = 'Incline Leg Press' AND is_system = true;
UPDATE exercises SET gif_key = '2012' WHERE name_en = 'Jump Squat' AND is_system = true;
UPDATE exercises SET gif_key = '2032' WHERE name_en = 'Kettlebell Goblet Squat' AND is_system = true;
UPDATE exercises SET gif_key = '2908' WHERE name_en = 'Low-Bar Back Squat' AND is_system = true;
UPDATE exercises SET gif_key = '2082' WHERE name_en = 'Machine Leg Extension' AND is_system = true;
UPDATE exercises SET gif_key = '9894' WHERE name_en = 'Narrow Stance Leg Press' AND is_system = true;
UPDATE exercises SET gif_key = '12391' WHERE name_en = 'Pendulum Squat' AND is_system = true;
UPDATE exercises SET gif_key = '3794' WHERE name_en = 'Pistol Squat' AND is_system = true;
UPDATE exercises SET gif_key = '3435' WHERE name_en = 'Single-Leg Machine Leg Extension' AND is_system = true;
UPDATE exercises SET gif_key = '2332' WHERE name_en = 'Sissy Squat' AND is_system = true;
UPDATE exercises SET gif_key = '2251' WHERE name_en = 'Smith Machine Bulgarian Split Squat' AND is_system = true;
UPDATE exercises SET gif_key = '2233' WHERE name_en = 'Smith Machine Squat' AND is_system = true;
UPDATE exercises SET gif_key = '13425' WHERE name_en = 'Walking Lunges' AND is_system = true;
UPDATE exercises SET gif_key = '10236' WHERE name_en = 'Assisted Nordic Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1538' WHERE name_en = 'Barbell Good Morning' AND is_system = true;
UPDATE exercises SET gif_key = '1579' WHERE name_en = 'Barbell Romanian Deadlift' AND is_system = true;
UPDATE exercises SET gif_key = '3412' WHERE name_en = 'Cable Leg Curl' AND is_system = true;
UPDATE exercises SET gif_key = '3206' WHERE name_en = 'Dumbbell Romanian Deadlift' AND is_system = true;
UPDATE exercises SET gif_key = '7148' WHERE name_en = 'Glute-Ham Raise' AND is_system = true;
UPDATE exercises SET gif_key = '7150' WHERE name_en = 'Lying Machine Leg Curl' AND is_system = true;
UPDATE exercises SET gif_key = '18424' WHERE name_en = 'Nordic Curl' AND is_system = true;
UPDATE exercises SET gif_key = '2090' WHERE name_en = 'Reverse Hyperextension' AND is_system = true;
UPDATE exercises SET gif_key = '1584' WHERE name_en = 'Seated Barbell Good Morning' AND is_system = true;
UPDATE exercises SET gif_key = '2096' WHERE name_en = 'Seated Machine Leg Curl' AND is_system = true;
UPDATE exercises SET gif_key = '3454' WHERE name_en = 'Single-Leg Machine Leg Curl' AND is_system = true;
UPDATE exercises SET gif_key = '3769' WHERE name_en = 'Single-Leg Romanian Deadlift' AND is_system = true;
UPDATE exercises SET gif_key = '8929' WHERE name_en = 'Sliding Leg Curl' AND is_system = true;
UPDATE exercises SET gif_key = '12132' WHERE name_en = 'Standing Machine Leg Curl' AND is_system = true;
UPDATE exercises SET gif_key = '1614' WHERE name_en = 'Stiff-Leg Deadlift' AND is_system = true;
UPDATE exercises SET gif_key = '13031' WHERE name_en = 'Swiss Ball Leg Curl' AND is_system = true;
UPDATE exercises SET gif_key = '16840' WHERE name_en = 'Banded Clamshell' AND is_system = true;
UPDATE exercises SET gif_key = '6563' WHERE name_en = 'Banded Hip Abduction' AND is_system = true;
UPDATE exercises SET gif_key = '3177' WHERE name_en = 'Barbell Glute Bridge' AND is_system = true;
UPDATE exercises SET gif_key = '1552' WHERE name_en = 'Barbell Hip Thrust' AND is_system = true;
UPDATE exercises SET gif_key = '2523' WHERE name_en = 'Barbell Sumo Squat' AND is_system = true;
UPDATE exercises SET gif_key = '11282' WHERE name_en = 'Cable Glute Kickback' AND is_system = true;
UPDATE exercises SET gif_key = '2357' WHERE name_en = 'Cable Hip Abduction' AND is_system = true;
UPDATE exercises SET gif_key = '1661' WHERE name_en = 'Cable Hip Adduction' AND is_system = true;
UPDATE exercises SET gif_key = '10927' WHERE name_en = 'Dumbbell Hip Thrust' AND is_system = true;
UPDATE exercises SET gif_key = '1872' WHERE name_en = 'Dumbbell Sumo Squat' AND is_system = true;
UPDATE exercises SET gif_key = '7069' WHERE name_en = 'Frog Pump' AND is_system = true;
UPDATE exercises SET gif_key = '5512' WHERE name_en = 'Glute Bridge' AND is_system = true;
UPDATE exercises SET gif_key = '16526' WHERE name_en = 'Machine Glute Kickback' AND is_system = true;
UPDATE exercises SET gif_key = '2094' WHERE name_en = 'Machine Hip Abduction' AND is_system = true;
UPDATE exercises SET gif_key = '2095' WHERE name_en = 'Machine Hip Adduction' AND is_system = true;
UPDATE exercises SET gif_key = '21543' WHERE name_en = 'Machine Hip Thrust' AND is_system = true;
UPDATE exercises SET gif_key = '8132' WHERE name_en = 'Single-Leg Glute Bridge' AND is_system = true;
UPDATE exercises SET gif_key = '18854' WHERE name_en = 'Single-Leg Hip Thrust' AND is_system = true;
UPDATE exercises SET gif_key = '3142' WHERE name_en = 'Barbell Standing Calf Raise' AND is_system = true;
UPDATE exercises SET gif_key = '23498' WHERE name_en = 'Calf Jumps' AND is_system = true;
UPDATE exercises SET gif_key = '2696' WHERE name_en = 'Donkey Calf Raise' AND is_system = true;
UPDATE exercises SET gif_key = '1918' WHERE name_en = 'Dumbbell Standing Calf Raise' AND is_system = true;
UPDATE exercises SET gif_key = '3153' WHERE name_en = 'Hack Squat Calf Raise' AND is_system = true;
UPDATE exercises SET gif_key = '3161' WHERE name_en = 'Leg Press Calf Raise' AND is_system = true;
UPDATE exercises SET gif_key = '2666' WHERE name_en = 'Seated Machine Calf Raise' AND is_system = true;
UPDATE exercises SET gif_key = '1910' WHERE name_en = 'Single-Leg Calf Raise' AND is_system = true;
UPDATE exercises SET gif_key = '2256' WHERE name_en = 'Smith Machine Calf Raise' AND is_system = true;
UPDATE exercises SET gif_key = '2102' WHERE name_en = 'Standing Machine Calf Raise' AND is_system = true;
UPDATE exercises SET gif_key = '2338' WHERE name_en = 'Ab Wheel Rollout' AND is_system = true;
UPDATE exercises SET gif_key = '15580' WHERE name_en = 'Bicycle Crunch' AND is_system = true;
UPDATE exercises SET gif_key = '2686' WHERE name_en = 'Bird Dog' AND is_system = true;
UPDATE exercises SET gif_key = '8680' WHERE name_en = 'Cable Crunch Machine' AND is_system = true;
UPDATE exercises SET gif_key = '5917' WHERE name_en = 'Cable Oblique Twist' AND is_system = true;
UPDATE exercises SET gif_key = '2652' WHERE name_en = 'Cable Pallof Press' AND is_system = true;
UPDATE exercises SET gif_key = '1769' WHERE name_en = 'Dead Bug' AND is_system = true;
UPDATE exercises SET gif_key = '1770' WHERE name_en = 'Decline Bench Crunch' AND is_system = true;
UPDATE exercises SET gif_key = '10125' WHERE name_en = 'Dragon Flag' AND is_system = true;
UPDATE exercises SET gif_key = '1908' WHERE name_en = 'Dumbbell Side Crunch' AND is_system = true;
UPDATE exercises SET gif_key = '1767' WHERE name_en = 'Floor Crunch' AND is_system = true;
UPDATE exercises SET gif_key = '4402' WHERE name_en = 'Front Plank' AND is_system = true;
UPDATE exercises SET gif_key = '5563' WHERE name_en = 'Hanging Knee Raise' AND is_system = true;
UPDATE exercises SET gif_key = '5542' WHERE name_en = 'Hanging Leg Raise' AND is_system = true;
UPDATE exercises SET gif_key = '24429' WHERE name_en = 'High Cable Woodchop' AND is_system = true;
UPDATE exercises SET gif_key = '4440' WHERE name_en = 'Hollow Hold' AND is_system = true;
UPDATE exercises SET gif_key = '1668' WHERE name_en = 'Kneeling Cable Crunch' AND is_system = true;
UPDATE exercises SET gif_key = '7591' WHERE name_en = 'L-Sit' AND is_system = true;
UPDATE exercises SET gif_key = '19083' WHERE name_en = 'Low Cable Woodchop' AND is_system = true;
UPDATE exercises SET gif_key = '10997' WHERE name_en = 'Lying Leg Raise' AND is_system = true;
UPDATE exercises SET gif_key = '2925' WHERE name_en = 'Machine Crunch' AND is_system = true;
UPDATE exercises SET gif_key = '2125' WHERE name_en = 'Mountain Climbers' AND is_system = true;
UPDATE exercises SET gif_key = '13494' WHERE name_en = 'Parallel Bar Leg Raise' AND is_system = true;
UPDATE exercises SET gif_key = '2164' WHERE name_en = 'Reverse Crunch' AND is_system = true;
UPDATE exercises SET gif_key = '4414' WHERE name_en = 'Side Plank' AND is_system = true;
UPDATE exercises SET gif_key = '1474' WHERE name_en = 'Sit-Up' AND is_system = true;
UPDATE exercises SET gif_key = '10012' WHERE name_en = 'Toes to Bar' AND is_system = true;
UPDATE exercises SET gif_key = '2307' WHERE name_en = 'V-Up' AND is_system = true;
UPDATE exercises SET gif_key = '2313' WHERE name_en = 'Weighted Crunch' AND is_system = true;
UPDATE exercises SET gif_key = '8019' WHERE name_en = 'Weighted Plank' AND is_system = true;
UPDATE exercises SET gif_key = '2327' WHERE name_en = 'Weighted Russian Twist' AND is_system = true;

-- 2. GIF en ejercicios CUSTOM del usuario (14)
UPDATE exercises SET gif_key = '3073' WHERE name_es = 'Press declinado máquina' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '6666' WHERE name_es = 'Incline Bench Press Machine' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '19256' WHERE name_es = 'Dislocaciones de hombros con goma' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '11278' WHERE name_es = 'Box Squat' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '4417' WHERE name_es = 'Wall Squat' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '3198' WHERE name_es = 'Single-Leg Incline Leg Press' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '4183' WHERE name_es = 'Correr en la calle' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '25074' WHERE name_es = 'Círculos de tobillos' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '13429' WHERE name_es = 'Círculos de brazos' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '9201' WHERE name_es = 'Sentadilla sin peso' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '12389' WHERE name_es = 'Zancada sin peso' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '12082' WHERE name_es = 'Círculos de cadera' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '1750' WHERE name_es = 'Círculos de rodillas' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';
UPDATE exercises SET gif_key = '8456' WHERE name_es = 'Balanceos de pierna' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0';

-- 3. Poda: soft-delete de redundantes/nicho (16)
UPDATE exercises SET deleted_at = now() WHERE name_es = 'Flexiones con Bosu' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0' AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Weighted Push-Ups' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Converging Machine Row' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Helms Row' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Neutral-Grip T-Bar Row' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Rope Lat Pulldown' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Incline Bench Lateral Raise' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Barbell 21s Curl' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'EZ-Bar Cable Curl' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Rope Cable Curl' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Weighted Dead Hang' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Leg Press' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_es = 'Lying Knee Extension' AND is_system = false AND user_id = '27a765cf-c3a6-4c98-94d9-21c2f3dec2a0' AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Side-Lying Hip Raise' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Tibialis Raise' AND is_system = true AND deleted_at IS NULL;
UPDATE exercises SET deleted_at = now() WHERE name_en = 'Weighted Sit-Up' AND is_system = true AND deleted_at IS NULL;

-- 4. Spanish Squat (custom) queda sin gif_key: Gym Visual no tiene ese ejercicio.
