-- ============================================
-- MIGRACIÓN 050: hispanizar instrucciones de ejercicios de sistema (LatAm -> España)
-- ============================================
-- El seed original (025, catálogo v5) describía los ejercicios en español latino.
-- Se normaliza a español de España (catálogo v6), en dos frentes:
--   1) Voseo -> tuteo: "empujá"->"empuja", "volvé"->"vuelve", "bajala"->"bájala",
--      "parate"->"colócate", "de vos"->"de ti"...
--   2) Léxico: "manija"->"asa", "hacia adelante"->"hacia delante",
--      "hacia afuera/adentro"->"hacia fuera/dentro", "toma"->"coge", "regresa"->"vuelve".
-- Solo cambia instructions.es; el bloque "en" y el resto de columnas quedan intactos.
-- Match por name_en (neutro; los name_es de prod pueden tener variaciones, ver
-- migración 049). 62 ejercicios afectados.
-- Idempotente: reaplicar deja el mismo estado peninsular.
-- ============================================

UPDATE exercises SET instructions = '{"es":{"setup":"Acuéstate en el banco con los ojos debajo de la barra. Agarra la barra algo más ancho que los hombros, pies firmes en el suelo y escápulas retraídas.","execution":"Desengancha la barra y bájala controladamente hasta el pecho medio. Empuja hacia arriba y ligeramente hacia atrás hasta bloquear los codos.","cues":["Aprieta las escápulas contra el banco","Codos a 45° del torso","Empuja el suelo con los pies"],"mistakes":["Rebotar la barra en el pecho","Levantar el trasero del banco","Codos abiertos a 90°"]},"en":{"setup":"Lie on the bench with eyes under the bar. Grip slightly wider than shoulder width, feet flat on the floor, shoulder blades retracted and pinched.","execution":"Unrack the bar and lower it under control to mid-chest. Press up and slightly back until elbows lock out.","cues":["Squeeze shoulder blades into the bench","Elbows at 45° from torso","Drive feet into the floor"],"mistakes":["Bouncing the bar off chest","Lifting hips off the bench","Flaring elbows to 90°"]}}'::jsonb
 WHERE name_en = 'Barbell Bench Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Ajusta el banco a 30-45°. Acuéstate con los pies firmes, escápulas retraídas y agarre algo más ancho que los hombros.","execution":"Desengancha la barra y bájala hasta la parte alta del pecho (clavículas). Empuja hacia arriba hasta extender los brazos completamente.","cues":["Pecho hacia arriba, arco en la espalda alta","Baja hasta las clavículas","No dejes que los codos se abran demasiado"],"mistakes":["Usar demasiada inclinación (>45° se vuelve press de hombros)","Dejar caer la barra sin control","Perder la retracción escapular"]},"en":{"setup":"Set the bench to 30-45°. Lie back with feet flat, shoulder blades retracted, grip slightly wider than shoulders.","execution":"Unrack and lower the bar to upper chest (collarbone level). Press up until arms are fully extended.","cues":["Chest up, arch in upper back","Lower to collarbone area","Keep elbows at roughly 45°"],"mistakes":["Too steep incline (>45° becomes shoulder press)","Dropping the bar without control","Losing shoulder blade retraction"]}}'::jsonb
 WHERE name_en = 'Incline Barbell Bench Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Ajusta el banco en declive (-15 a -30°). Asegura las piernas en los soportes. Agarre algo más ancho que los hombros.","execution":"Desengancha la barra y bájala hasta la parte baja del pecho. Empuja hacia arriba hasta bloquear los codos.","cues":["Escápulas juntas y abajo","Baja hacia la parte baja del esternón","Movimiento controlado en todo momento"],"mistakes":["Usar demasiado decline (riesgo de congestión en la cabeza)","Dejar que la barra se desvíe hacia la cara","No asegurar bien las piernas"]},"en":{"setup":"Set bench to decline (-15 to -30°). Secure legs under pads. Grip slightly wider than shoulders.","execution":"Unrack and lower the bar to lower chest. Press up until elbows lock out.","cues":["Shoulder blades pinched and depressed","Lower to lower sternum","Controlled tempo throughout"],"mistakes":["Too steep a decline (blood rush to head)","Letting the bar drift toward face","Not securing legs properly"]}}'::jsonb
 WHERE name_en = 'Decline Barbell Bench Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Siéntate en el banco con una mancuerna en cada muslo. Acuéstate llevando las mancuernas al pecho con las rodillas. Pies firmes, escápulas retraídas.","execution":"Empuja las mancuernas hacia arriba hasta que los brazos estén extendidos. Baja controladamente hasta que los codos queden a la altura del pecho o ligeramente por debajo.","cues":["Que las mancuernas no choquen arriba","Codos a 45°, no dejarlos caer","Aprieta el pecho arriba"],"mistakes":["Bajar demasiado y forzar el hombro","No controlar la bajada","Arquear excesivamente la espalda baja"]},"en":{"setup":"Sit with a dumbbell on each thigh. Lie back, using knees to kick them into position at chest level. Feet flat, shoulder blades retracted.","execution":"Press dumbbells up until arms are extended. Lower under control until elbows are at chest height or slightly below.","cues":["Don''t clank dumbbells at the top","Elbows at 45°, don''t let them drop","Squeeze chest at the top"],"mistakes":["Going too deep and stressing shoulders","Losing control on the descent","Excessive lower back arch"]}}'::jsonb
 WHERE name_en = 'Dumbbell Bench Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Banco a 30-45°. Lleva las mancuernas a posición con ayuda de las rodillas. Escápulas retraídas, pies firmes en el suelo.","execution":"Empuja las mancuernas hacia arriba y ligeramente hacia dentro. Baja controladamente hasta sentir un estiramiento en el pecho alto.","cues":["Pecho bien abierto","Codos apuntando al suelo, no hacia atrás","Siente el estiramiento abajo"],"mistakes":["Demasiada inclinación del banco","Mancuernas chocan agresivamente arriba","Perder tensión en el pecho al bajar"]},"en":{"setup":"Bench at 30-45°. Kick dumbbells into position with knees. Shoulder blades retracted, feet planted.","execution":"Press dumbbells up and slightly inward. Lower under control until you feel a stretch in the upper chest.","cues":["Keep chest open and proud","Elbows pointing down, not back","Feel the stretch at the bottom"],"mistakes":["Bench angle too steep","Aggressively clanking dumbbells at top","Losing chest tension on the way down"]}}'::jsonb
 WHERE name_en = 'Incline Dumbbell Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Banco en declive, piernas aseguradas. Lleva las mancuernas al pecho desde los muslos. Escápulas retraídas.","execution":"Empuja las mancuernas hacia arriba hasta extender los brazos. Baja hasta que los codos estén a la altura del torso.","cues":["Controla todo el recorrido","Aprieta el pecho abajo del esternón","Codos a 45°"],"mistakes":["Dejar caer las mancuernas sin control","No asegurar bien las piernas","Usar impulso en lugar de fuerza"]},"en":{"setup":"Decline bench with legs secured. Bring dumbbells to chest from thighs. Shoulder blades retracted.","execution":"Press dumbbells up until arms are extended. Lower until elbows are at torso height.","cues":["Control the full range of motion","Squeeze lower chest","Elbows at 45°"],"mistakes":["Dropping dumbbells without control","Legs not properly secured","Using momentum instead of muscle"]}}'::jsonb
 WHERE name_en = 'Decline Dumbbell Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Acuéstate en el banco con agarre al ancho de los hombros o ligeramente más cerrado. Escápulas retraídas, pies firmes.","execution":"Desengancha la barra y bájala hasta la parte baja del pecho manteniendo los codos pegados al torso. Empuja hacia arriba hasta bloquear.","cues":["Codos pegados al cuerpo","Baja hacia el esternón bajo","No cerrar tanto que duelan las muñecas"],"mistakes":["Agarre demasiado cerrado (daña muñecas)","Abrir los codos como en press normal","Rebotar la barra en el pecho"]},"en":{"setup":"Lie on the bench with hands at shoulder width or slightly narrower. Shoulder blades retracted, feet flat.","execution":"Unrack and lower the bar to lower chest keeping elbows tucked close to your body. Press up to lockout.","cues":["Keep elbows tucked","Lower to lower sternum","Don''t go so narrow it hurts wrists"],"mistakes":["Grip too narrow (wrist strain)","Flaring elbows like a regular bench","Bouncing off chest"]}}'::jsonb
 WHERE name_en = 'Close-Grip Bench Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Posiciona el banco plano dentro de la Smith con la barra alineada al pecho medio. Escápulas retraídas, pies firmes.","execution":"Desengancha la barra, baja controladamente hasta el pecho. Empuja hasta extender los brazos y gira para enganchar.","cues":["Alinea bien el banco antes de empezar","Mismo patrón de codos a 45°","Controla la bajada, la máquina no frena por ti"],"mistakes":["Mala alineación del banco con la barra","Confiar demasiado en la guía y perder la técnica","No bloquear bien la barra al terminar"]},"en":{"setup":"Position a flat bench inside the Smith machine with the bar aligned to mid-chest. Shoulder blades retracted, feet flat.","execution":"Unrack the bar, lower under control to chest. Press up to full extension and twist to re-rack.","cues":["Align the bench properly before starting","Same 45° elbow angle as free bench","Control the descent—the machine won''t brake for you"],"mistakes":["Poor bench alignment with the bar path","Over-relying on the guided path and losing form","Not locking the bar properly when done"]}}'::jsonb
 WHERE name_en = 'Smith Machine Bench Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Banco a 30-45° dentro de la Smith, barra alineada con la parte alta del pecho. Escápulas retraídas, pies firmes.","execution":"Desengancha y baja la barra a las clavículas. Empuja hasta extender completamente.","cues":["Pecho arriba, buen arco torácico","Baja a la zona de las clavículas","Movimiento fluido y controlado"],"mistakes":["Banco mal posicionado bajo la barra","Inclinación demasiado alta","Dejar que la barra caiga sin control"]},"en":{"setup":"Bench at 30-45° inside the Smith machine, bar aligned with upper chest. Shoulder blades retracted, feet flat.","execution":"Unrack and lower the bar to collarbone area. Press to full lockout.","cues":["Chest up, good thoracic arch","Lower to collarbone zone","Smooth, controlled movement"],"mistakes":["Bench poorly positioned under the bar","Incline too steep","Letting the bar drop without control"]}}'::jsonb
 WHERE name_en = 'Smith Machine Incline Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Ajusta el asiento para que las asas queden a la altura del pecho medio. Espalda apoyada, pies firmes en el suelo.","execution":"Empuja las asas hacia delante hasta extender los brazos sin bloquear violentamente. Vuelve controladamente sintiendo el estiramiento.","cues":["Pecho abierto, hombros atrás","No bloquees violentamente los codos","Aprieta el pecho en la contracción"],"mistakes":["Asiento demasiado alto o bajo","Despegar la espalda del respaldo","Usar impulso con el torso"]},"en":{"setup":"Adjust the seat so handles are at mid-chest height. Back flat against pad, feet planted on the floor.","execution":"Push handles forward until arms are extended without violent lockout. Return under control, feeling the stretch.","cues":["Chest open, shoulders back","Don''t slam into lockout","Squeeze the chest on contraction"],"mistakes":["Seat too high or low","Back coming off the pad","Using torso momentum"]}}'::jsonb
 WHERE name_en = 'Machine Chest Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Ajusta el asiento para que las asas estén a la altura del pecho. Espalda apoyada, pies firmes.","execution":"Empuja las asas hacia delante y hacia dentro (convergen). Vuelve controladamente hasta sentir un buen estiramiento en el pecho.","cues":["Aprovecha la convergencia para apretar el pecho al final","Escápulas contra el respaldo","Fase excéntrica lenta"],"mistakes":["No aprovechar el recorrido convergente","Despegar la espalda al empujar","Ir demasiado rápido en la vuelta"]},"en":{"setup":"Adjust seat so handles are at chest height. Back against pad, feet flat.","execution":"Push handles forward and inward (they converge). Return under control until you feel a good chest stretch.","cues":["Use the converging path to squeeze at the top","Shoulder blades against the pad","Slow eccentric phase"],"mistakes":["Not taking advantage of the converging motion","Back lifting off the pad","Rushing the return phase"]}}'::jsonb
 WHERE name_en = 'Converging Machine Chest Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Acuéstate en banco plano con una mancuerna en cada mano, brazos extendidos arriba con los codos ligeramente flexionados.","execution":"Abre los brazos en arco hasta sentir un estiramiento en el pecho. Vuelve al centro apretando el pecho, como si abrazaras un árbol.","cues":["Codos ligeramente flexionados siempre","Movimiento en arco, no de press","Aprieta el pecho arriba"],"mistakes":["Extender los codos completamente (riesgo de lesión)","Bajar demasiado y forzar el hombro","Convertirlo en un press (flexionar mucho los codos)"]},"en":{"setup":"Lie on a flat bench holding dumbbells above you with arms extended and elbows slightly bent.","execution":"Open arms in an arc until you feel a chest stretch. Bring them back together squeezing the chest, like hugging a tree.","cues":["Keep a slight bend in elbows throughout","Arc motion, not a press","Squeeze chest at the top"],"mistakes":["Fully extending elbows (injury risk)","Going too deep and straining shoulders","Turning it into a press (bending elbows too much)"]}}'::jsonb
 WHERE name_en = 'Dumbbell Fly' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Banco a 30-45°. Mancuernas arriba con codos ligeramente flexionados, palmas enfrentadas.","execution":"Abre los brazos en arco bajando hasta sentir estiramiento en el pecho superior. Vuelve apretando el pecho.","cues":["Mantén la flexión de codos constante","Siente el estiramiento en el pecho alto","Movimiento lento y controlado"],"mistakes":["Dejar caer los brazos sin control","Cambiar el ángulo de los codos durante el movimiento","Peso excesivo que impide buen rango"]},"en":{"setup":"Bench at 30-45°. Dumbbells above with slightly bent elbows, palms facing each other.","execution":"Open arms in an arc until you feel a stretch in the upper chest. Return by squeezing the chest.","cues":["Maintain constant elbow bend","Feel the stretch in upper chest","Slow, controlled movement"],"mistakes":["Letting arms drop without control","Changing elbow angle during the movement","Too heavy—sacrificing range of motion"]}}'::jsonb
 WHERE name_en = 'Incline Dumbbell Fly' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Banco en declive con piernas aseguradas. Mancuernas arriba, codos ligeramente flexionados, palmas enfrentadas.","execution":"Abre los brazos en arco hasta sentir estiramiento en la parte baja del pecho. Vuelve juntando las mancuernas arriba.","cues":["Codos con flexión fija","Aprieta la parte baja del pecho al cerrar","No dejes que la gravedad te gane"],"mistakes":["Perder el control en la fase excéntrica","Piernas mal aseguradas","Usar demasiado peso para este ejercicio de aislamiento"]},"en":{"setup":"Decline bench with legs secured. Dumbbells above, elbows slightly bent, palms facing.","execution":"Open arms in an arc until you feel a stretch in the lower chest. Return by bringing dumbbells together at top.","cues":["Fixed elbow bend throughout","Squeeze the lower chest when closing","Don''t let gravity win"],"mistakes":["Losing control on the eccentric","Legs not secured properly","Too heavy for an isolation exercise"]}}'::jsonb
 WHERE name_en = 'Decline Dumbbell Fly' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Poleas en posición alta. Colócate en el centro, un paso adelante, torso ligeramente inclinado. Agarra un asa con cada mano.","execution":"Con los codos ligeramente flexionados, lleva las manos hacia abajo y al centro en un arco. Aprieta el pecho abajo y vuelve controladamente.","cues":["Inclina el torso un poco hacia delante","Cruza las manos ligeramente abajo","Siente el estiramiento al abrir"],"mistakes":["Usar los brazos en lugar del pecho","Cuerpo demasiado erguido","Mover el torso para generar impulso"]},"en":{"setup":"Cables set high. Stand centered, one step forward, torso slightly leaned forward. Grab a handle in each hand.","execution":"With slightly bent elbows, bring hands down and together in an arc. Squeeze the chest at the bottom and return under control.","cues":["Lean torso slightly forward","Cross hands slightly at the bottom","Feel the stretch when opening"],"mistakes":["Using arms instead of chest","Standing too upright","Swinging torso for momentum"]}}'::jsonb
 WHERE name_en = 'High Cable Crossover' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Poleas en posición baja. Colócate en el centro, un paso adelante. Agarra las asas con palmas hacia arriba/adelante.","execution":"Lleva las manos hacia arriba y al centro en un arco, como si hicieras doble bíceps. Aprieta el pecho arriba y baja controladamente.","cues":["Siente la contracción en el pecho superior","Codos fijos con ligera flexión","Fase excéntrica lenta"],"mistakes":["Tirar con los bíceps","Encoger los hombros","Usar demasiado peso y perder la técnica"]},"en":{"setup":"Cables set low. Stand centered, one step forward. Grab handles with palms facing up/forward.","execution":"Bring hands up and together in an arc, like a double bicep pose. Squeeze upper chest at top and lower under control.","cues":["Feel the contraction in upper chest","Fixed elbows with slight bend","Slow eccentric phase"],"mistakes":["Pulling with biceps","Shrugging shoulders","Too heavy, losing form"]}}'::jsonb
 WHERE name_en = 'Low Cable Crossover' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Poleas a la altura del pecho. Colócate en el centro, un paso adelante, torso recto o ligeramente inclinado.","execution":"Lleva las manos hacia delante y al centro a la altura del pecho. Aprieta el pecho y vuelve controladamente.","cues":["Las manos se juntan al frente a la altura del esternón","Movimiento de abrazo","Mantén la tensión constante"],"mistakes":["Flexionar demasiado los codos (se convierte en press)","No mantener la misma altura durante el recorrido","Balancearse para mover el peso"]},"en":{"setup":"Cables at chest height. Stand centered, one step forward, torso straight or slightly leaned.","execution":"Bring hands forward and together at chest height. Squeeze chest and return under control.","cues":["Hands meet at sternum height","Hugging motion","Keep constant tension"],"mistakes":["Bending elbows too much (turns into a press)","Not maintaining the same height throughout","Swaying to move the weight"]}}'::jsonb
 WHERE name_en = 'Mid Cable Crossover' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Ajusta el asiento para que los brazos queden a la altura del pecho. Espalda contra el respaldo, pies firmes. Agarra las asas o apoya los antebrazos en las almohadillas.","execution":"Junta los brazos al frente apretando el pecho. Vuelve controladamente hasta sentir un buen estiramiento sin forzar el hombro.","cues":["Aprieta fuerte al juntar","No dejes que el peso te abra de golpe","Espalda siempre contra el respaldo"],"mistakes":["Asiento mal ajustado","Abrir demasiado y forzar los hombros","Usar impulso del torso"]},"en":{"setup":"Adjust seat so arms are at chest height. Back against pad, feet flat. Grab handles or rest forearms on pads.","execution":"Bring arms together in front squeezing the chest. Return under control to a comfortable stretch without forcing shoulders.","cues":["Squeeze hard when arms meet","Don''t let the weight snap you open","Back always against the pad"],"mistakes":["Seat improperly adjusted","Opening too far and straining shoulders","Using torso momentum"]}}'::jsonb
 WHERE name_en = 'Pec Deck Machine Fly' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Acuéstate en un banco plano. Sostén una mancuerna con ambas manos por un extremo, brazos extendidos sobre el pecho.","execution":"Baja la mancuerna por detrás de la cabeza en arco manteniendo los codos ligeramente flexionados. Cuando sientas el estiramiento, vuelve a la posición inicial apretando pecho y dorsales.","cues":["Codos fijos, el movimiento es del hombro","Siente el estiramiento en pecho y dorsales","No bajes más de lo que tu movilidad permita"],"mistakes":["Flexionar los codos y convertirlo en press francés","Bajar demasiado y forzar el hombro","Arquear excesivamente la espalda baja"]},"en":{"setup":"Lie on a flat bench. Hold one dumbbell with both hands by one end, arms extended over chest.","execution":"Lower the dumbbell behind your head in an arc with slightly bent elbows. When you feel the stretch, return to start by engaging chest and lats.","cues":["Fixed elbows—movement is from the shoulder","Feel stretch in chest and lats","Don''t go beyond your mobility"],"mistakes":["Bending elbows and turning it into a skull crusher","Going too deep and straining shoulders","Excessive lower back arch"]}}'::jsonb
 WHERE name_en = 'Dumbbell Pullover' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Polea alta con barra recta o cuerda. Colócate de frente a la polea, un paso atrás, torso inclinado. Brazos extendidos agarrando el accesorio arriba.","execution":"Con los codos casi bloqueados, tira el accesorio hacia abajo en arco hasta los muslos. Vuelve arriba controladamente.","cues":["Brazos casi rectos todo el tiempo","Siente la contracción en pecho y dorsales","Movimiento desde el hombro, no el codo"],"mistakes":["Flexionar los codos y tirar con tríceps","Estar demasiado cerca de la polea","Usar el peso del cuerpo para tirar"]},"en":{"setup":"High cable with straight bar or rope. Face the cable, step back, lean torso forward. Arms extended gripping the attachment above.","execution":"With nearly locked elbows, pull the attachment down in an arc to your thighs. Return up under control.","cues":["Arms almost straight throughout","Feel contraction in chest and lats","Movement from the shoulder, not the elbow"],"mistakes":["Bending elbows and pulling with triceps","Standing too close to the cable","Using body weight to pull"]}}'::jsonb
 WHERE name_en = 'Cable Pullover' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Ajusta el asiento para que los hombros queden alineados con el eje de la máquina. Espalda contra el respaldo, pies firmes. Apoya los codos/antebrazos en las almohadillas.","execution":"Empuja las almohadillas hacia abajo en arco hasta la zona del abdomen. Vuelve arriba controladamente sin dejar que el peso te lleve.","cues":["Siente pecho y dorsales trabajando","No dejes que el peso te estire de golpe","Movimiento fluido"],"mistakes":["Asiento mal ajustado (hombros desalineados del eje)","Usar impulso","Rango de movimiento excesivo"]},"en":{"setup":"Adjust seat so shoulders align with the machine''s pivot point. Back against pad, feet flat. Rest elbows/forearms on pads.","execution":"Push pads down in an arc toward your abdomen. Return up under control without letting the weight pull you.","cues":["Feel chest and lats working together","Don''t let the weight snap you back","Smooth, fluid movement"],"mistakes":["Seat poorly adjusted (shoulders misaligned with pivot)","Using momentum","Excessive range of motion"]}}'::jsonb
 WHERE name_en = 'Machine Pullover' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Agarra las barras paralelas con los brazos extendidos. Inclina el torso hacia delante para enfatizar pecho. Cruza los pies atrás.","execution":"Baja flexionando los codos hasta que el brazo quede paralelo al suelo o sientas un buen estiramiento. Empuja hacia arriba hasta extender los brazos.","cues":["Inclinación hacia delante para pecho","Baja hasta 90° en los codos mínimo","Codos ligeramente abiertos"],"mistakes":["Torso muy erguido (trabaja más tríceps que pecho)","Bajar demasiado sin movilidad suficiente","Balancearse o usar impulso"]},"en":{"setup":"Grip parallel bars with arms extended. Lean torso forward to emphasize chest. Cross feet behind you.","execution":"Lower by bending elbows until upper arm is parallel to the floor or you feel a good stretch. Push up to full extension.","cues":["Lean forward for chest emphasis","Lower to at least 90° elbow bend","Elbows slightly flared"],"mistakes":["Too upright (shifts work to triceps)","Going too deep without sufficient mobility","Swinging or using momentum"]}}'::jsonb
 WHERE name_en = 'Parallel Bar Dips' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Coloca el cinturón de lastre con el peso elegido. Agarra las barras con brazos extendidos, torso inclinado hacia delante.","execution":"Baja controladamente hasta que el brazo quede paralelo al suelo. Empuja hacia arriba de forma explosiva pero controlada.","cues":["El peso cuelga quieto, sin balanceo","Misma inclinación que fondos sin peso","Controla especialmente la bajada"],"mistakes":["Balancear el peso con el cuerpo","Reducir el rango de movimiento por el peso extra","Agregar peso antes de dominar el peso corporal"]},"en":{"setup":"Attach dip belt with chosen weight. Grip bars with arms extended, torso leaning forward.","execution":"Lower under control until upper arm is parallel to the floor. Push up explosively but controlled.","cues":["Weight hangs still, no swinging","Same forward lean as bodyweight dips","Control the descent especially"],"mistakes":["Swinging the weight with your body","Reducing range of motion due to extra weight","Adding weight before mastering bodyweight"]}}'::jsonb
 WHERE name_en = 'Weighted Parallel Bar Dips' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Manos en el suelo algo más anchas que los hombros. Cuerpo recto de cabeza a talones, abdomen activado.","execution":"Baja el pecho hasta casi tocar el suelo flexionando los codos. Empuja hacia arriba hasta extender los brazos completamente.","cues":["Cuerpo recto como una tabla","Codos a 45°, no abiertos","Aprieta el abdomen todo el tiempo"],"mistakes":["Cadera caída o levantada","Rango de movimiento incompleto","Cabeza colgando hacia abajo"]},"en":{"setup":"Hands on the floor slightly wider than shoulders. Body in a straight line from head to heels, core braced.","execution":"Lower your chest to nearly touch the floor by bending elbows. Push up until arms are fully extended.","cues":["Body straight like a plank","Elbows at 45°, not flared","Brace core throughout"],"mistakes":["Hips sagging or piking up","Incomplete range of motion","Head drooping down"]}}'::jsonb
 WHERE name_en = 'Push-Ups' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Manos en una superficie elevada (banco, cajón). Cuerpo recto, pies en el suelo.","execution":"Baja el pecho hacia la superficie elevada y empuja hacia arriba. Más fácil que flexiones normales, trabaja más pecho bajo.","cues":["Cuerpo recto, no doblar la cadera","Pecho toca o casi toca la superficie","Codos a 45°"],"mistakes":["Cadera caída","No bajar lo suficiente","Superficie inestable"]},"en":{"setup":"Hands on an elevated surface (bench, box). Body straight, feet on the floor.","execution":"Lower chest toward the elevated surface and push back up. Easier than standard push-ups, emphasizes lower chest.","cues":["Body straight, don''t bend at hips","Chest touches or nearly touches surface","Elbows at 45°"],"mistakes":["Sagging hips","Not going low enough","Unstable surface"]}}'::jsonb
 WHERE name_en = 'Incline Push-Ups' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Pies elevados en un banco o cajón, manos en el suelo algo más anchas que los hombros. Cuerpo recto.","execution":"Baja el pecho al suelo y empuja hacia arriba. Más difícil que flexiones normales, trabaja más pecho superior.","cues":["Cuanto más alto los pies, más trabaja el pecho alto","Cuerpo recto de pies a cabeza","Cabeza en posición neutra"],"mistakes":["Cadera levantada en forma de V","Mirar hacia arriba y forzar el cuello","Superficie inestable para los pies"]},"en":{"setup":"Feet elevated on a bench or box, hands on the floor slightly wider than shoulders. Body straight.","execution":"Lower chest to the floor and push up. Harder than standard push-ups, emphasizes upper chest.","cues":["Higher feet = more upper chest work","Straight body from feet to head","Neutral head position"],"mistakes":["Hips piked up in a V-shape","Looking up and straining neck","Unstable foot surface"]}}'::jsonb
 WHERE name_en = 'Decline Push-Ups' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Manos juntas debajo del pecho formando un diamante con los pulgares e índices. Cuerpo recto, abdomen activado.","execution":"Baja el pecho hasta las manos y empuja hacia arriba. El rango de movimiento es menor, el énfasis en tríceps es alto.","cues":["Codos pegados al cuerpo","Baja hasta tocar las manos con el pecho","Abdomen muy apretado"],"mistakes":["Abrir los codos como en flexión normal","Cuerpo no recto","No completar el rango de movimiento"]},"en":{"setup":"Hands together under chest forming a diamond with thumbs and index fingers. Body straight, core braced.","execution":"Lower chest to your hands and push back up. Shorter range of motion, high tricep emphasis.","cues":["Elbows tucked close to body","Lower until chest touches hands","Core very tight"],"mistakes":["Flaring elbows like a regular push-up","Body not straight","Incomplete range of motion"]}}'::jsonb
 WHERE name_en = 'Diamond Push-Ups' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Acuéstate en el suelo con rodillas flexionadas. Lleva las mancuernas a posición de press. Los codos tocarán el suelo abajo.","execution":"Empuja las mancuernas hacia arriba hasta extender los brazos. Baja hasta que los codos toquen suavemente el suelo y repite sin rebotar.","cues":["Los codos tocan el suelo, no rebotan","Buena pausa abajo para eliminar impulso","Codos a 45°"],"mistakes":["Rebotar los codos en el suelo","No pausar abajo","Codos demasiado abiertos"]},"en":{"setup":"Lie on the floor with knees bent. Bring dumbbells to press position. Elbows will touch the floor at bottom.","execution":"Press dumbbells up until arms are extended. Lower until elbows gently touch the floor and repeat without bouncing.","cues":["Elbows touch the floor, no bounce","Good pause at bottom to kill momentum","Elbows at 45°"],"mistakes":["Bouncing elbows off the floor","Not pausing at the bottom","Elbows flared too wide"]}}'::jsonb
 WHERE name_en = 'Dumbbell Floor Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Acuéstate en banco plano. Junta las mancuernas con las caras planas tocándose (hexagonales), palmas enfrentadas.","execution":"Empuja las mancuernas hacia arriba manteniéndolas juntas todo el tiempo. Baja al pecho sin separarlas.","cues":["Las mancuernas se aprietan entre sí todo el recorrido","Siente la contracción interna del pecho","Codos pegados al cuerpo"],"mistakes":["Separar las mancuernas durante el movimiento","No apretar las mancuernas entre sí","Usar mancuernas redondas (se resbalan)"]},"en":{"setup":"Lie on a flat bench. Press the flat faces of hex dumbbells together, palms facing each other.","execution":"Press dumbbells up while keeping them pressed together throughout. Lower to chest without separating them.","cues":["Dumbbells squeezed together the entire time","Feel the inner chest contraction","Elbows tucked close to body"],"mistakes":["Letting dumbbells separate during the movement","Not actively pressing them together","Using round dumbbells (they slip)"]}}'::jsonb
 WHERE name_en = 'Dumbbell Hex Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Polea a la altura del pecho. Colócate de espaldas, un pie adelante para estabilidad. Agarra el asa con una mano a la altura del pecho.","execution":"Empuja el asa hacia delante y ligeramente hacia dentro. Vuelve controladamente sin dejar que el torso rote.","cues":["Core activado para no rotar","Empuja desde el pecho, no el hombro","Pie adelantado del mismo lado que trabaja"],"mistakes":["Rotar el torso para ayudar","Perder estabilidad del core","Usar demasiado peso y compensar"]},"en":{"setup":"Cable at chest height. Stand with your back to the machine, staggered stance for stability. Grab handle at chest level with one hand.","execution":"Push the handle forward and slightly inward. Return under control without letting your torso rotate.","cues":["Core braced to prevent rotation","Push from the chest, not the shoulder","Lead foot on the working side"],"mistakes":["Rotating the torso to assist","Losing core stability","Too heavy, compensating with body"]}}'::jsonb
 WHERE name_en = 'Single-Arm Cable Chest Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Apoya una mano y la rodilla del mismo lado en un banco. El otro pie en el suelo. Coge la mancuerna con el brazo libre, colgando perpendicular al suelo.","execution":"Tira de la mancuerna hacia la cadera llevando el codo hacia el techo. Aprieta el dorsal arriba. Baja con control hasta extensión completa.","cues":["Codo al techo, no hacia fuera","Siente el dorsal, no solo el brazo","Torso estable, sin rotar"],"mistakes":["Rotar el torso para subir más peso","Tirar solo con el bíceps","No bajar la mancuerna completamente"]},"en":{"setup":"Place one hand and the same-side knee on a bench. Other foot on the floor. Hold the dumbbell with the free arm, hanging perpendicular to the ground.","execution":"Row the dumbbell toward your hip, driving the elbow toward the ceiling. Squeeze the lat at the top. Lower with control to full extension.","cues":["Elbow to the ceiling, not out to the side","Feel the lat, not just the arm","Stable torso, no twisting"],"mistakes":["Rotating the torso to heave more weight","Pulling with bicep only","Not lowering the dumbbell fully"]}}'::jsonb
 WHERE name_en = 'Single-Arm Dumbbell Row' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Coloca un banco inclinado a unos 30-45°. Túmbate boca abajo con el pecho apoyado. Coge una mancuerna en cada mano con los brazos colgando.","execution":"Rema las mancuernas hacia los lados del torso retrayendo las escápulas. Aprieta arriba. Baja con control hasta extensión completa.","cues":["Pecho pegado al banco","Retrae las escápulas antes de tirar","Controla la bajada, no dejes caer"],"mistakes":["Despegar el pecho para coger impulso","No completar la retracción escapular","Rango de movimiento incompleto"]},"en":{"setup":"Set an incline bench to 30-45°. Lie face down with chest supported. Hold a dumbbell in each hand, arms hanging.","execution":"Row the dumbbells to the sides of your torso, retracting shoulder blades. Squeeze at the top. Lower with control to full extension.","cues":["Chest stays on the bench","Retract shoulder blades before pulling","Control the descent, don''t drop"],"mistakes":["Lifting chest off the bench for momentum","Incomplete scapular retraction","Partial range of motion"]}}'::jsonb
 WHERE name_en = 'Incline Bench Dumbbell Row' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"De pie con mancuernas a los lados, palmas mirando al cuerpo. Pies a la anchura de los hombros.","execution":"Flexiona un brazo supinando la muñeca (girando la palma hacia arriba) durante la subida. Aprieta el bíceps arriba y baja controladamente. Alterna con el otro brazo.","cues":["Supina durante la subida, no antes","Un brazo trabaja mientras el otro descansa","Codos fijos al costado"],"mistakes":["Balancear el torso de un lado a otro","No supinar completamente","Mover los codos hacia delante"]},"en":{"setup":"Stand with dumbbells at your sides, palms facing your body. Feet shoulder-width apart.","execution":"Curl one arm up while supinating (rotating palm upward) during the lift. Squeeze the bicep at top and lower under control. Alternate with the other arm.","cues":["Supinate during the curl, not before","One arm works while the other rests","Elbows fixed at your sides"],"mistakes":["Swinging the torso side to side","Not fully supinating","Moving elbows forward"]}}'::jsonb
 WHERE name_en = 'Alternating Dumbbell Curl' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Polea alta con barra recta. Colócate de frente, agarre prono (palmas abajo) al ancho de los hombros. Codos pegados al torso.","execution":"Empuja la barra hacia abajo extendiendo los codos hasta bloquear. Vuelve arriba controladamente sin mover los codos de su posición.","cues":["Codos clavados al costado del cuerpo","Aprieta los tríceps abajo","Solo se mueven los antebrazos"],"mistakes":["Abrir los codos del cuerpo","Inclinarse sobre la barra usando peso corporal","Subir demasiado y perder tensión"]},"en":{"setup":"High cable with straight bar. Face the machine, overhand grip at shoulder width. Elbows pinned to your sides.","execution":"Push the bar down by extending elbows to full lockout. Return up under control without moving elbows from position.","cues":["Elbows glued to your sides","Squeeze triceps at the bottom","Only forearms move"],"mistakes":["Elbows drifting away from body","Leaning over the bar using bodyweight","Going too high and losing tension"]}}'::jsonb
 WHERE name_en = 'Straight Bar Tricep Pushdown' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Polea alta con barra V. Agarre neutro (palmas enfrentadas), codos pegados al cuerpo.","execution":"Empuja hacia abajo extendiendo los codos completamente. Vuelve arriba sin dejar que los codos se muevan de posición.","cues":["El agarre neutro es más cómodo para las muñecas","Aprieta fuerte abajo","Codos fijos"],"mistakes":["Mover los codos adelante-atrás","Usar impulso del cuerpo","No extender completamente abajo"]},"en":{"setup":"High cable with V-bar. Neutral grip (palms facing), elbows pinned to body.","execution":"Push down by fully extending elbows. Return up without letting elbows move from position.","cues":["Neutral grip is easier on wrists","Squeeze hard at the bottom","Fixed elbows"],"mistakes":["Elbows swinging forward and back","Using body momentum","Not fully extending at the bottom"]}}'::jsonb
 WHERE name_en = 'V-Bar Tricep Pushdown' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Polea alta con cuerda. Agarra los extremos con agarre neutro. Codos pegados al cuerpo, torso ligeramente inclinado.","execution":"Empuja hacia abajo y separa los extremos de la cuerda al final del movimiento para máxima contracción. Vuelve arriba controladamente.","cues":["Abre la cuerda abajo para apretar más","Codos fijos al costado","Siente el pico de contracción al separar"],"mistakes":["No separar la cuerda abajo","Codos alejándose del cuerpo","Usar el peso del cuerpo para empujar"]},"en":{"setup":"High cable with rope. Grip the ends with neutral grip. Elbows pinned, torso slightly leaned forward.","execution":"Push down and spread the rope apart at the bottom for maximum contraction. Return up under control.","cues":["Split the rope at the bottom for extra squeeze","Elbows fixed at your sides","Feel the peak contraction when splitting"],"mistakes":["Not splitting the rope at the bottom","Elbows drifting from body","Using bodyweight to push"]}}'::jsonb
 WHERE name_en = 'Rope Tricep Pushdown' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Polea alta con barra recta o EZ. Agarre supino (palmas hacia arriba), codos pegados al torso.","execution":"Empuja la barra hacia abajo extendiendo los codos. Aprieta los tríceps abajo y vuelve controladamente.","cues":["Palmas mirando al techo","Codos pegados, no se mueven","Enfatiza la cabeza medial del tríceps"],"mistakes":["Muñecas flexionadas hacia atrás","Agarre demasiado ancho","Usar peso excesivo (este agarre es más débil)"]},"en":{"setup":"High cable with straight or EZ bar. Underhand grip (palms up), elbows pinned to torso.","execution":"Push the bar down extending elbows. Squeeze triceps at the bottom and return under control.","cues":["Palms facing the ceiling","Elbows pinned, don''t move","Emphasizes the medial tricep head"],"mistakes":["Wrists bending backward","Grip too wide","Too heavy (this grip is weaker)"]}}'::jsonb
 WHERE name_en = 'Underhand Tricep Pushdown' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Polea alta con asa de una mano. Colócate de frente, codo pegado al costado. La otra mano puede apoyarse en la estructura.","execution":"Empuja hacia abajo extendiendo el codo completamente. Vuelve arriba sin dejar que el codo se mueva.","cues":["Codo fijo como bisagra","Aprieta el tríceps al bloquear","Puedes rotar ligeramente al final"],"mistakes":["Mover el codo para ayudar","Rotar el torso","Usar demasiado peso y compensar"]},"en":{"setup":"High cable with single handle. Face the machine, elbow pinned to your side. Other hand can hold the frame.","execution":"Push down by fully extending the elbow. Return up without letting the elbow move.","cues":["Elbow fixed like a hinge","Squeeze tricep at lockout","Slight rotation at the end is okay"],"mistakes":["Moving the elbow to assist","Rotating the torso","Too heavy, compensating"]}}'::jsonb
 WHERE name_en = 'Single-Arm Tricep Pushdown' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Acuéstate en banco plano. Agarra la barra EZ en la curva interna con agarre cerrado. Brazos extendidos sobre la frente.","execution":"Baja la barra flexionando los codos hasta que quede cerca de la frente o ligeramente detrás de la cabeza. Extiende los codos para volver arriba.","cues":["Los codos apuntan al techo, no se abren","Baja a la frente o detrás de la cabeza","Movimiento solo de los codos"],"mistakes":["Abrir los codos hacia fuera","Bajar la barra a la nariz (peligroso)","Mover los hombros para ayudar"]},"en":{"setup":"Lie on a flat bench. Grip the EZ bar on the inner curve with a narrow grip. Arms extended over your forehead.","execution":"Lower the bar by bending elbows until it''s near the forehead or slightly behind the head. Extend elbows to return up.","cues":["Elbows point at the ceiling, don''t flare","Lower to forehead or behind head","Movement only from the elbows"],"mistakes":["Flaring elbows outward","Lowering to the nose (dangerous)","Moving shoulders to assist"]}}'::jsonb
 WHERE name_en = 'EZ-Bar Skull Crusher' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Acuéstate en banco plano. Una mancuerna en cada mano con agarre neutro (palmas enfrentadas). Brazos extendidos sobre la cara.","execution":"Baja las mancuernas flexionando los codos hasta los lados de la cabeza. Extiende para volver a la posición inicial.","cues":["Agarre neutro es más amigable para los codos","Codos fijos apuntando al techo","Controla cada mancuerna por separado"],"mistakes":["Dejar caer las mancuernas sin control","Codos abriéndose","Usar excesivo impulso de hombros"]},"en":{"setup":"Lie on a flat bench. One dumbbell in each hand, neutral grip (palms facing). Arms extended above your face.","execution":"Lower dumbbells by bending elbows to the sides of your head. Extend to return to start.","cues":["Neutral grip is more elbow-friendly","Elbows fixed pointing at ceiling","Control each dumbbell independently"],"mistakes":["Dropping dumbbells without control","Elbows flaring out","Excessive shoulder momentum"]}}'::jsonb
 WHERE name_en = 'Dumbbell Skull Crusher' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Acuéstate en banco plano. Agarra la barra recta con agarre cerrado (ancho de hombros o menos). Brazos extendidos sobre la frente.","execution":"Baja la barra flexionando los codos hacia la frente o detrás de la cabeza. Extiende para volver arriba.","cues":["Codos paralelos, no se abren","Baja controladamente","La barra recta exige más a las muñecas, cuida la posición"],"mistakes":["Muñecas dobladas hacia atrás","Codos abriéndose","Dejar caer la barra sin control"]},"en":{"setup":"Lie on a flat bench. Grip the straight bar with a narrow grip (shoulder width or less). Arms extended above forehead.","execution":"Lower the bar by bending elbows toward forehead or behind head. Extend to return up.","cues":["Elbows parallel, don''t flare","Lower under control","Straight bar is harder on wrists—watch position"],"mistakes":["Wrists bending backward","Elbows flaring out","Dropping the bar without control"]}}'::jsonb
 WHERE name_en = 'Barbell Skull Crusher' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Sentado o de pie. Sostén una mancuerna con ambas manos por un extremo, brazos extendidos por encima de la cabeza.","execution":"Baja la mancuerna detrás de la cabeza flexionando los codos. Cuando sientas el estiramiento, extiende los codos para volver arriba.","cues":["Codos apuntan al techo, pegados a la cabeza","Siente el estiramiento en la cabeza larga del tríceps","Core activado para no arquear"],"mistakes":["Codos abriéndose hacia fuera","Arquear excesivamente la espalda baja","Mover los hombros para asistir"]},"en":{"setup":"Seated or standing. Hold one dumbbell with both hands by one end, arms fully extended overhead.","execution":"Lower the dumbbell behind your head by bending elbows. When you feel the stretch, extend elbows to return up.","cues":["Elbows point to ceiling, close to head","Feel the stretch on the long head","Core braced to avoid arching"],"mistakes":["Elbows flaring outward","Excessive lower back arch","Moving shoulders to assist"]}}'::jsonb
 WHERE name_en = 'Overhead Dumbbell Tricep Extension' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Sentado o de pie. Una mancuerna en una mano, brazo extendido sobre la cabeza. La otra mano puede estabilizar el codo.","execution":"Baja la mancuerna detrás de la cabeza flexionando el codo. Extiende para volver arriba.","cues":["Codo apunta al techo sin moverse","Puedes usar la otra mano para estabilizar","Siente el estiramiento en cada rep"],"mistakes":["Codo moviéndose hacia delante","Inclinar el torso para compensar","No usar rango completo"]},"en":{"setup":"Seated or standing. One dumbbell in one hand, arm extended overhead. Other hand can stabilize the elbow.","execution":"Lower the dumbbell behind your head by bending the elbow. Extend to return up.","cues":["Elbow points to ceiling without moving","Use other hand to stabilize if needed","Feel the stretch each rep"],"mistakes":["Elbow drifting forward","Leaning torso to compensate","Not using full range of motion"]}}'::jsonb
 WHERE name_en = 'Single-Arm Overhead Dumbbell Tricep Extension' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Polea baja con barra o asa. De espaldas a la polea, un paso adelante. Brazos sobre la cabeza, codos flexionados.","execution":"Extiende los codos empujando hacia arriba y adelante. Vuelve controladamente sintiendo el estiramiento.","cues":["Codos fijos cerca de la cabeza","La polea da tensión constante, aprovéchala","Postura adelantada con un pie"],"mistakes":["Codos abriéndose","Moverse demasiado lejos de la polea","Usar el torso para impulsar"]},"en":{"setup":"Low cable with bar or handle. Face away from the machine, step forward. Arms overhead, elbows bent.","execution":"Extend elbows pushing up and forward. Return under control feeling the stretch.","cues":["Elbows fixed near your head","Cable provides constant tension—use it","Staggered stance for stability"],"mistakes":["Elbows flaring","Standing too far from the cable","Using torso to generate force"]}}'::jsonb
 WHERE name_en = 'Overhead Cable Tricep Extension' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Polea baja con cuerda. De espaldas a la polea, un paso adelante. Agarra la cuerda detrás de la cabeza con codos flexionados.","execution":"Extiende los codos y separa los extremos de la cuerda al final para máxima contracción. Vuelve controladamente.","cues":["Abre la cuerda arriba para extra contracción","Codos pegados a la cabeza","Inclina el torso ligeramente hacia delante"],"mistakes":["No separar la cuerda al extender","Codos moviéndose","Perder estabilidad del core"]},"en":{"setup":"Low cable with rope. Face away, step forward. Grab rope behind your head with elbows bent.","execution":"Extend elbows and spread the rope apart at the top for maximum contraction. Return under control.","cues":["Split rope at top for extra squeeze","Elbows close to head","Slight forward torso lean"],"mistakes":["Not splitting the rope when extending","Elbows moving around","Losing core stability"]}}'::jsonb
 WHERE name_en = 'Overhead Rope Cable Tricep Extension' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Inclínate apoyando una mano y rodilla en un banco. Brazo de trabajo con el codo a 90°, pegado al torso, paralelo al suelo.","execution":"Extiende el codo hacia atrás hasta que el brazo quede completamente recto. Aprieta el tríceps arriba y vuelve a 90°.","cues":["Brazo superior paralelo al suelo, no se mueve","Aprieta fuerte al extender","Movimiento lento y controlado"],"mistakes":["Balancear la mancuerna con impulso","El codo cae y pierde la posición","Usar demasiado peso (este ejercicio es de aislamiento)"]},"en":{"setup":"Lean forward with one hand and knee on a bench. Working arm bent at 90°, upper arm parallel to the floor and pinned to torso.","execution":"Extend the elbow back until arm is fully straight. Squeeze tricep at the top and return to 90°.","cues":["Upper arm parallel to floor, doesn''t move","Squeeze hard at extension","Slow, controlled movement"],"mistakes":["Swinging the dumbbell with momentum","Elbow dropping and losing position","Too heavy (this is an isolation move)"]}}'::jsonb
 WHERE name_en = 'Dumbbell Tricep Kickback' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Polea baja con asa. Inclínate hacia delante, codo a 90° pegado al costado, brazo paralelo al suelo.","execution":"Extiende el codo hacia atrás contra la resistencia de la polea. Aprieta y vuelve controladamente.","cues":["La polea mantiene tensión constante, mejor que mancuerna","Codo fijo, solo mueve el antebrazo","Aprieta al final"],"mistakes":["Pararse demasiado erguido","Mover el brazo completo en lugar de solo el codo","Ir demasiado rápido"]},"en":{"setup":"Low cable with handle. Lean forward, elbow at 90° pinned to your side, upper arm parallel to floor.","execution":"Extend elbow back against cable resistance. Squeeze and return under control.","cues":["Cable keeps constant tension—better than dumbbells","Elbow fixed, only forearm moves","Squeeze at the end"],"mistakes":["Standing too upright","Moving the whole arm instead of just the elbow","Going too fast"]}}'::jsonb
 WHERE name_en = 'Cable Tricep Kickback' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Manos en el borde de un banco detrás de ti, dedos hacia delante. Piernas extendidas o flexionadas según nivel. Trasero cerca del banco.","execution":"Baja flexionando los codos hasta ~90°. Empuja hacia arriba hasta extender los brazos.","cues":["Mantente cerca del banco","Codos hacia atrás, no hacia fuera","Baja hasta 90° en los codos"],"mistakes":["Codos abriéndose hacia los lados","Bajar demasiado y forzar los hombros","Alejarse demasiado del banco"]},"en":{"setup":"Hands on the edge of a bench behind you, fingers forward. Legs extended or bent depending on level. Hips close to the bench.","execution":"Lower by bending elbows to about 90°. Push up until arms are fully extended.","cues":["Stay close to the bench","Elbows point backward, not outward","Lower to 90° at the elbows"],"mistakes":["Elbows flaring to the sides","Going too deep and straining shoulders","Drifting too far from the bench"]}}'::jsonb
 WHERE name_en = 'Bench Dips' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Misma posición que fondos en banco, pero con un disco o peso en los muslos. Piernas en otro banco para mayor rango.","execution":"Baja controladamente hasta ~90° en los codos. Empuja hacia arriba hasta extender.","cues":["El peso debe estar estable en los muslos","Mismo patrón que sin peso","Controla especialmente la bajada"],"mistakes":["Peso inestable que se resbala","Reducir rango por el peso extra","Bajar demasiado y forzar hombros"]},"en":{"setup":"Same position as bench dips but with a plate or weight on your thighs. Feet on another bench for greater range.","execution":"Lower under control to about 90° at elbows. Push up to full extension.","cues":["Weight must be stable on thighs","Same pattern as unweighted","Control the descent especially"],"mistakes":["Unstable weight sliding off","Reducing range due to extra load","Going too deep and straining shoulders"]}}'::jsonb
 WHERE name_en = 'Weighted Bench Dips' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Ajusta el asiento para que los codos queden alineados con el eje de la máquina. Espalda contra el respaldo, agarra las asas.","execution":"Extiende los codos empujando las asas hacia abajo hasta bloquear. Vuelve controladamente sin perder tensión.","cues":["Codos alineados con el eje de rotación","Extensión completa abajo","Controla la vuelta"],"mistakes":["Asiento mal ajustado (codos desalineados)","No extender completamente","Dejar que el peso caiga sin control"]},"en":{"setup":"Adjust seat so elbows align with the machine''s pivot point. Back against pad, grip the handles.","execution":"Extend elbows pushing handles down to lockout. Return under control without losing tension.","cues":["Elbows aligned with the pivot","Full extension at the bottom","Control the return"],"mistakes":["Seat poorly adjusted (elbows misaligned)","Not fully extending","Letting the weight drop without control"]}}'::jsonb
 WHERE name_en = 'Machine Tricep Extension' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Acuéstate en banco plano. Agarra la barra con agarre al ancho de hombros o ligeramente cerrado. Brazos extendidos sobre el pecho alto.","execution":"Baja la barra combinando flexión de codo y descenso hacia la barbilla/cuello. Es un híbrido entre press cerrado y press francés. Extiende para volver.","cues":["Los codos bajan y se flexionan simultáneamente","La barra va hacia la barbilla, no al pecho","Movimiento híbrido, no es ni press ni francés puro"],"mistakes":["Convertirlo en un press cerrado normal","Convertirlo en un press francés normal","Usar demasiado peso sin dominar la técnica"]},"en":{"setup":"Lie on a flat bench. Grip the bar at shoulder width or slightly narrower. Arms extended above upper chest.","execution":"Lower the bar combining elbow flexion and descent toward chin/neck area. It''s a hybrid of close-grip press and skull crusher. Extend to return.","cues":["Elbows lower and bend simultaneously","Bar goes toward chin, not chest","Hybrid movement—neither pure press nor pure crusher"],"mistakes":["Turning it into a regular close-grip press","Turning it into a regular skull crusher","Too heavy before mastering the technique"]}}'::jsonb
 WHERE name_en = 'JM Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Acuéstate en banco plano con mancuernas sostenidas arriba, brazos extendidos, palmas mirando a los pies.","execution":"Baja las mancuernas hacia el pecho flexionando los codos hacia dentro (los codos apuntan hacia fuera). Los extremos internos de las mancuernas bajan al pecho. Extiende para volver.","cues":["Los codos van hacia fuera, no hacia la cabeza","Las mancuernas bajan al centro del pecho","Movimiento único, cuesta acostumbrarse"],"mistakes":["Confundirlo con un press francés (dirección incorrecta de codos)","Dejar caer las mancuernas en el pecho","Usar demasiado peso antes de dominar el patrón"]},"en":{"setup":"Lie on a flat bench holding dumbbells above you, arms extended, palms facing your feet.","execution":"Lower the dumbbells toward your chest by bending elbows outward. The inner ends of the dumbbells come down to chest. Extend to return.","cues":["Elbows flare outward, not toward head","Dumbbells lower to the center of chest","Unique movement pattern—takes practice"],"mistakes":["Confusing it with a skull crusher (wrong elbow direction)","Dropping dumbbells onto chest","Too heavy before mastering the pattern"]}}'::jsonb
 WHERE name_en = 'Dumbbell Tate Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Coge una mancuerna pesada o kettlebell en cada mano. De pie erguido con hombros atrás y abajo. Core activado.","execution":"Camina con pasos cortos y controlados manteniendo la postura erguida. Aprieta fuerte el agarre. Mantén los hombros estables y nivelados. Recorre la distancia o tiempo objetivo.","cues":["Postura alta, hombros atrás","Agarre de muerte: aprieta como si se te fueran a caer","Pasos cortos y rápidos"],"mistakes":["Inclinarse hacia los lados","Pasos demasiado largos que desestabilizan","Dejar caer los hombros hacia delante"]},"en":{"setup":"Pick up a heavy dumbbell or kettlebell in each hand. Stand tall with shoulders back and down. Core braced.","execution":"Walk with short, controlled steps while maintaining upright posture. Grip hard. Keep shoulders stable and level. Cover the target distance or time.","cues":["Tall posture, shoulders back","Death grip — squeeze like they''re about to slip","Short, quick steps"],"mistakes":["Leaning to one side","Steps too long, causing instability","Letting shoulders roll forward"]}}'::jsonb
 WHERE name_en = 'Farmer''s Walk' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Coge el gripper con una mano. Coloca la parte fija contra la palma y la parte móvil contra los dedos. Codo puede estar flexionado o brazo recto.","execution":"Cierra el gripper apretando con fuerza hasta que las asas se toquen. Mantén cerrado 1 segundo. Abre con control. Repite.","cues":["Cierre completo: las asas se tocan","Pausa con el gripper cerrado","Apertura controlada, no dejes que se abra solo"],"mistakes":["No cerrar completamente (repetición no válida)","Usar la otra mano para ayudar al cierre","Hacer repeticiones demasiado rápidas sin control"]},"en":{"setup":"Hold the gripper with one hand. Place the fixed handle against your palm and the moving handle against your fingers. Elbow can be bent or arm straight.","execution":"Close the gripper by squeezing hard until the handles touch. Hold closed for 1 second. Open with control. Repeat.","cues":["Full close: handles must touch","Pause with the gripper closed","Controlled opening, don''t let it spring open"],"mistakes":["Not closing completely (rep doesn''t count)","Using the other hand to assist the close","Repping too fast without control"]}}'::jsonb
 WHERE name_en = 'Hand Gripper' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Siéntate en la máquina con la espalda apoyada en el respaldo y los pies sujetos. Agarra las asas a la altura del pecho o detrás de la cabeza según el diseño.","execution":"Flexiona el tronco hacia delante contrayendo el abdomen. Mantén la contracción un instante abajo y vuelve arriba con control.","cues":["Redondea la espalda al bajar, no empujes con los brazos","Exhala fuerte al contraer","Controla la fase de vuelta"],"mistakes":["Empujar con los brazos en vez de usar el abdomen","Ir demasiado rápido sin controlar el movimiento","No recorrer el rango completo"]},"en":{"setup":"Sit in the machine with your back against the pad and feet secured. Grip the handles at chest height or behind the head depending on the design.","execution":"Crunch your torso forward contracting your abs. Hold the contraction briefly at the bottom and return up with control.","cues":["Round the back as you crunch, don''t push with arms","Exhale hard as you contract","Control the return phase"],"mistakes":["Pushing with arms instead of using the abs","Going too fast without controlling the movement","Not using full range of motion"]}}'::jsonb
 WHERE name_en = 'Cable Crunch Machine' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Siéntate en la máquina, ajusta la almohadilla al pecho y sujeta bien los pies. Espalda apoyada en el respaldo.","execution":"Flexiona el tronco hacia delante empujando con el abdomen contra la resistencia. Mantén la contracción abajo y vuelve lentamente.","cues":["Piensa en acercar el esternón al ombligo","Exhala al bajar, inhala al subir","Movimiento lento y controlado"],"mistakes":["Usar el peso de los brazos para bajar","Rebotar abajo para subir más fácil","Arquear la espalda en la vuelta"]},"en":{"setup":"Sit in the machine, adjust the chest pad and secure your feet. Back against the backrest.","execution":"Crunch your torso forward pushing with your abs against the resistance. Hold the contraction at the bottom and return slowly.","cues":["Think about bringing your sternum toward your belly button","Exhale going down, inhale going up","Slow and controlled movement"],"mistakes":["Using arm weight to push down","Bouncing at the bottom to come up easier","Arching the back on the return"]}}'::jsonb
 WHERE name_en = 'Machine Crunch' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Ajusta el asiento para que las asas queden a la altura del pecho bajo. Espalda y cabeza apoyadas, pies firmes.","execution":"Empuja las asas hacia delante y ligeramente abajo hasta extender los brazos sin bloquear de golpe. Vuelve controlando el estiramiento.","cues":["Asas a la altura del pecho bajo","Codos a ~45°, no del todo abiertos","Aprieta el pecho al final"],"mistakes":["Asiento demasiado alto","Despegar la espalda del respaldo","Bloquear los codos de golpe"]},"en":{"setup":"Set the seat so the handles sit at lower-chest height. Back and head against the pad, feet planted.","execution":"Press the handles forward and slightly down to full extension without slamming lockout. Return under control, feeling the stretch.","cues":["Handles at lower-chest level","Elbows ~45°, not fully flared","Squeeze the chest at the end"],"mistakes":["Seat set too high","Back lifting off the pad","Snapping elbows into lockout"]}}'::jsonb
 WHERE name_en = 'Machine Decline Chest Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Ajusta el asiento para que las asas queden a la altura del pecho alto/clavícula. Espalda apoyada, pies firmes.","execution":"Empuja las asas hacia arriba y adelante hasta casi extender los brazos. Baja controlando hasta sentir el pecho alto estirado.","cues":["Asas a la altura del pecho alto","Enfatiza la porción clavicular del pecho","No bloquees los codos de golpe"],"mistakes":["Asiento demasiado bajo (trabaja como plano)","Arquear la lumbar despegando la espalda","Recorrido corto"]},"en":{"setup":"Set the seat so the handles sit at upper-chest/collarbone height. Back against the pad, feet planted.","execution":"Press the handles up and forward to near-lockout. Lower under control until you feel the upper chest stretch.","cues":["Handles at upper-chest level","Emphasize the upper (clavicular) chest","Don''t slam the elbows to lockout"],"mistakes":["Seat too low (becomes a flat press)","Arching and lifting the back off the pad","Short range of motion"]}}'::jsonb
 WHERE name_en = 'Machine Incline Chest Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"Coge una banda elástica con las manos más anchas que los hombros, brazos extendidos por delante del cuerpo.","execution":"Con los codos rectos, lleva la banda por encima de la cabeza hasta la espalda baja y vuelve al frente. La banda se estira lo justo para pasar sin dolor.","cues":["Brazos siempre extendidos","Agarre más ancho = más fácil","Movimiento lento y controlado"],"mistakes":["Agarre demasiado estrecho (fuerza el hombro)","Flexionar los codos para hacer trampa","Ir rápido o con tirones"]},"en":{"setup":"Hold a resistance band with hands wider than shoulder-width, arms straight out in front.","execution":"Keeping the elbows straight, take the band up and over your head to your lower back, then return to the front. It stretches just enough to pass through pain-free.","cues":["Keep the arms fully straight","Wider grip = easier","Slow and controlled"],"mistakes":["Grip too narrow (strains the shoulder)","Bending the elbows to cheat","Rushing or jerking"]}}'::jsonb
 WHERE name_en = 'Band Shoulder Dislocates' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"En la prensa inclinada, coloca un pie centrado en la plataforma. La otra pierna descansa a un lado. Espalda y cadera apoyadas.","execution":"Desbloquea y baja controlando hasta ~90° de rodilla. Empuja con el pie hasta casi extender, sin bloquear la rodilla.","cues":["Pie centrado para que la rodilla no se vaya hacia dentro","Baja controlado, sin rebote","No bloquees la rodilla arriba"],"mistakes":["Despegar la cadera del asiento","Recorrido corto","Bloquear la rodilla de golpe"]},"en":{"setup":"On the incline leg press, place one foot centered on the platform, the other leg resting to the side. Back and hips against the pad.","execution":"Unlock and lower under control to ~90° knee bend. Press through the foot to near-extension without locking the knee.","cues":["Foot centered so the knee doesn''t cave","Lower controlled, no bounce","Don''t lock the knee at the top"],"mistakes":["Hips lifting off the seat","Short range of motion","Snapping the knee to lockout"]}}'::jsonb
 WHERE name_en = 'Single-Leg Incline Leg Press' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"De pie, brazos extendidos en cruz a la altura de los hombros.","execution":"Dibuja círculos con los brazos, empezando pequeños y agrandándolos. Realiza hacia delante y luego hacia atrás.","cues":["Brazos rectos y activos","De círculos pequeños a grandes","Igual en ambos sentidos"],"mistakes":["Encoger los hombros","Brazos flojos o flexionados","Ir a tirones"]},"en":{"setup":"Standing, arms extended out to the sides at shoulder height.","execution":"Draw circles with the arms, starting small and growing larger. Do them forward, then backward.","cues":["Arms straight and active","Small to large circles","Equal both directions"],"mistakes":["Shrugging the shoulders","Loose or bent arms","Jerky motion"]}}'::jsonb
 WHERE name_en = 'Arm Circles' AND is_system = true;

UPDATE exercises SET instructions = '{"es":{"setup":"De pie, pies al ancho de hombros, puntas ligeramente hacia fuera. Brazos al frente para equilibrar.","execution":"Baja llevando la cadera atrás y abajo hasta que los muslos queden al menos paralelos. Sube empujando con los talones.","cues":["Pecho erguido, mirada al frente","Rodillas siguen la línea de los pies","Peso repartido en todo el pie"],"mistakes":["Rodillas hacia dentro","Levantar los talones","No bajar hasta paralelo"]},"en":{"setup":"Stand with feet shoulder-width, toes slightly out. Arms in front for balance.","execution":"Lower by sitting your hips back and down until thighs are at least parallel. Stand up driving through your heels.","cues":["Chest tall, eyes forward","Knees track over the feet","Weight spread across the whole foot"],"mistakes":["Knees caving in","Heels lifting","Not reaching parallel"]}}'::jsonb
 WHERE name_en = 'Bodyweight Squat' AND is_system = true;

-- Verificación: los 62 name_en deben existir como ejercicios de sistema.
-- Si faltan, el nombre en prod difiere y ese ejercicio no se hispanizó (revisar manualmente).
DO $$
DECLARE
  expected int := 62;
  matched  int;
BEGIN
  SELECT count(*) INTO matched
  FROM exercises
  WHERE is_system = true AND name_en IN (
    'Barbell Bench Press',
    'Incline Barbell Bench Press',
    'Decline Barbell Bench Press',
    'Dumbbell Bench Press',
    'Incline Dumbbell Press',
    'Decline Dumbbell Press',
    'Close-Grip Bench Press',
    'Smith Machine Bench Press',
    'Smith Machine Incline Press',
    'Machine Chest Press',
    'Converging Machine Chest Press',
    'Dumbbell Fly',
    'Incline Dumbbell Fly',
    'Decline Dumbbell Fly',
    'High Cable Crossover',
    'Low Cable Crossover',
    'Mid Cable Crossover',
    'Pec Deck Machine Fly',
    'Dumbbell Pullover',
    'Cable Pullover',
    'Machine Pullover',
    'Parallel Bar Dips',
    'Weighted Parallel Bar Dips',
    'Push-Ups',
    'Incline Push-Ups',
    'Decline Push-Ups',
    'Diamond Push-Ups',
    'Dumbbell Floor Press',
    'Dumbbell Hex Press',
    'Single-Arm Cable Chest Press',
    'Single-Arm Dumbbell Row',
    'Incline Bench Dumbbell Row',
    'Alternating Dumbbell Curl',
    'Straight Bar Tricep Pushdown',
    'V-Bar Tricep Pushdown',
    'Rope Tricep Pushdown',
    'Underhand Tricep Pushdown',
    'Single-Arm Tricep Pushdown',
    'EZ-Bar Skull Crusher',
    'Dumbbell Skull Crusher',
    'Barbell Skull Crusher',
    'Overhead Dumbbell Tricep Extension',
    'Single-Arm Overhead Dumbbell Tricep Extension',
    'Overhead Cable Tricep Extension',
    'Overhead Rope Cable Tricep Extension',
    'Dumbbell Tricep Kickback',
    'Cable Tricep Kickback',
    'Bench Dips',
    'Weighted Bench Dips',
    'Machine Tricep Extension',
    'JM Press',
    'Dumbbell Tate Press',
    'Farmer''s Walk',
    'Hand Gripper',
    'Cable Crunch Machine',
    'Machine Crunch',
    'Machine Decline Chest Press',
    'Machine Incline Chest Press',
    'Band Shoulder Dislocates',
    'Single-Leg Incline Leg Press',
    'Arm Circles',
    'Bodyweight Squat'
  );
  IF matched < expected THEN
    RAISE WARNING 'Hispanización 050: encontrados %/% ejercicios por name_en; revisar nombres en prod', matched, expected;
  ELSE
    RAISE NOTICE 'Hispanización 050: % ejercicios actualizados correctamente', matched;
  END IF;
END $$;
